export enum Secretaria {
    GABINETE,
    PROCURADORIA_JURÍDICA,
    SMS_SECRETARIA_MUNICIPAL_DE_SAÚDE_PÚBLICA,
    SEGOV_SECRETARIA_MUNICIPAL_DE_GOVERNO_E_POLÍTICAS_PÚBLICAS,
    SMAS_SECRETARIA_MUNICIPAL_DE_ASSISTÊNCIA_SOCIAL,
    SEMEC_SECRETARIA_MUNICIPAL_DE_EDUCAÇÃO_E_CULTURA,
    SEMEA_SECRETARIA_MUNICIPAL_DE_MEIO_AMBIENTE_E_AGRONEGÓCIO,
    SEINTRA_SECRETARIA_MUNICIPAL_DE_INFRAESTRUTURA_TRANSPORTE_E_TRÂNSITO,
    SEJUVEL_SECRETARIA_MUNICIPAL_DE_ESPORTE_JUVENTUDE_E_LAZER,
    SEFIRC_SECRETARIA_MUNICIPAL_DE_FINANÇAS_RECEITA_E_CONTROLE,
    SEMAD_SECRETARIA_MUNICIPAL_DE_ADMINISTRAÇÃO,
    SEDECT_SECRETARIA_MUNICIPAL_DE_DESENVOLVIMENTO_ECONÔMICO_CIÊNCIA_E_TECNOLOGIA,
}